/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125ServicesRouteImport } from './routes/{-$locale}/services'
import { Route as Char123LocaleChar125ProductsRouteImport } from './routes/{-$locale}/products'
import { Route as Char123LocaleChar125IndustriesRouteImport } from './routes/{-$locale}/industries'
import { Route as Char123LocaleChar125FreelancingRouteImport } from './routes/{-$locale}/freelancing'
import { Route as Char123LocaleChar125DashboardRouteImport } from './routes/{-$locale}/dashboard'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125BusinessRouteImport } from './routes/{-$locale}/business'
import { Route as Char123LocaleChar125AuthRouteImport } from './routes/{-$locale}/auth'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125ServicesServiceSlugRouteImport } from './routes/{-$locale}/services/$serviceSlug'
import { Route as Char123LocaleChar125ProductsProductSlugRouteImport } from './routes/{-$locale}/products/$productSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ServicesRoute =
  Char123LocaleChar125ServicesRouteImport.update({
    id: '/{-$locale}/services',
    path: '/{-$locale}/services',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ProductsRoute =
  Char123LocaleChar125ProductsRouteImport.update({
    id: '/{-$locale}/products',
    path: '/{-$locale}/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndustriesRoute =
  Char123LocaleChar125IndustriesRouteImport.update({
    id: '/{-$locale}/industries',
    path: '/{-$locale}/industries',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125FreelancingRoute =
  Char123LocaleChar125FreelancingRouteImport.update({
    id: '/{-$locale}/freelancing',
    path: '/{-$locale}/freelancing',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DashboardRoute =
  Char123LocaleChar125DashboardRouteImport.update({
    id: '/{-$locale}/dashboard',
    path: '/{-$locale}/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/{-$locale}/contact',
    path: '/{-$locale}/contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125BusinessRoute =
  Char123LocaleChar125BusinessRouteImport.update({
    id: '/{-$locale}/business',
    path: '/{-$locale}/business',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthRoute =
  Char123LocaleChar125AuthRouteImport.update({
    id: '/{-$locale}/auth',
    path: '/{-$locale}/auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/{-$locale}/about',
    path: '/{-$locale}/about',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ServicesServiceSlugRoute =
  Char123LocaleChar125ServicesServiceSlugRouteImport.update({
    id: '/$serviceSlug',
    path: '/$serviceSlug',
    getParentRoute: () => Char123LocaleChar125ServicesRoute,
  } as any)
const Char123LocaleChar125ProductsProductSlugRoute =
  Char123LocaleChar125ProductsProductSlugRouteImport.update({
    id: '/$productSlug',
    path: '/$productSlug',
    getParentRoute: () => Char123LocaleChar125ProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRoute
  '/{-$locale}/business': typeof Char123LocaleChar125BusinessRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/freelancing': typeof Char123LocaleChar125FreelancingRoute
  '/{-$locale}/industries': typeof Char123LocaleChar125IndustriesRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsRouteWithChildren
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/products/$productSlug': typeof Char123LocaleChar125ProductsProductSlugRoute
  '/{-$locale}/services/$serviceSlug': typeof Char123LocaleChar125ServicesServiceSlugRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRoute
  '/{-$locale}/business': typeof Char123LocaleChar125BusinessRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/freelancing': typeof Char123LocaleChar125FreelancingRoute
  '/{-$locale}/industries': typeof Char123LocaleChar125IndustriesRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsRouteWithChildren
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/products/$productSlug': typeof Char123LocaleChar125ProductsProductSlugRoute
  '/{-$locale}/services/$serviceSlug': typeof Char123LocaleChar125ServicesServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRoute
  '/{-$locale}/business': typeof Char123LocaleChar125BusinessRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/freelancing': typeof Char123LocaleChar125FreelancingRoute
  '/{-$locale}/industries': typeof Char123LocaleChar125IndustriesRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsRouteWithChildren
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/products/$productSlug': typeof Char123LocaleChar125ProductsProductSlugRoute
  '/{-$locale}/services/$serviceSlug': typeof Char123LocaleChar125ServicesServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/auth'
    | '/{-$locale}/business'
    | '/{-$locale}/contact'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/freelancing'
    | '/{-$locale}/industries'
    | '/{-$locale}/products'
    | '/{-$locale}/services'
    | '/{-$locale}/'
    | '/{-$locale}/products/$productSlug'
    | '/{-$locale}/services/$serviceSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/auth'
    | '/{-$locale}/business'
    | '/{-$locale}/contact'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/freelancing'
    | '/{-$locale}/industries'
    | '/{-$locale}/products'
    | '/{-$locale}/services'
    | '/{-$locale}'
    | '/{-$locale}/products/$productSlug'
    | '/{-$locale}/services/$serviceSlug'
  id:
    | '__root__'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/auth'
    | '/{-$locale}/business'
    | '/{-$locale}/contact'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/freelancing'
    | '/{-$locale}/industries'
    | '/{-$locale}/products'
    | '/{-$locale}/services'
    | '/{-$locale}/'
    | '/{-$locale}/products/$productSlug'
    | '/{-$locale}/services/$serviceSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125AuthRoute: typeof Char123LocaleChar125AuthRoute
  Char123LocaleChar125BusinessRoute: typeof Char123LocaleChar125BusinessRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125DashboardRoute: typeof Char123LocaleChar125DashboardRoute
  Char123LocaleChar125FreelancingRoute: typeof Char123LocaleChar125FreelancingRoute
  Char123LocaleChar125IndustriesRoute: typeof Char123LocaleChar125IndustriesRoute
  Char123LocaleChar125ProductsRoute: typeof Char123LocaleChar125ProductsRouteWithChildren
  Char123LocaleChar125ServicesRoute: typeof Char123LocaleChar125ServicesRouteWithChildren
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/services': {
      id: '/{-$locale}/services'
      path: '/{-$locale}/services'
      fullPath: '/{-$locale}/services'
      preLoaderRoute: typeof Char123LocaleChar125ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/products': {
      id: '/{-$locale}/products'
      path: '/{-$locale}/products'
      fullPath: '/{-$locale}/products'
      preLoaderRoute: typeof Char123LocaleChar125ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/industries': {
      id: '/{-$locale}/industries'
      path: '/{-$locale}/industries'
      fullPath: '/{-$locale}/industries'
      preLoaderRoute: typeof Char123LocaleChar125IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/freelancing': {
      id: '/{-$locale}/freelancing'
      path: '/{-$locale}/freelancing'
      fullPath: '/{-$locale}/freelancing'
      preLoaderRoute: typeof Char123LocaleChar125FreelancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/dashboard': {
      id: '/{-$locale}/dashboard'
      path: '/{-$locale}/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/{-$locale}/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/business': {
      id: '/{-$locale}/business'
      path: '/{-$locale}/business'
      fullPath: '/{-$locale}/business'
      preLoaderRoute: typeof Char123LocaleChar125BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/auth': {
      id: '/{-$locale}/auth'
      path: '/{-$locale}/auth'
      fullPath: '/{-$locale}/auth'
      preLoaderRoute: typeof Char123LocaleChar125AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/{-$locale}/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/services/$serviceSlug': {
      id: '/{-$locale}/services/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/{-$locale}/services/$serviceSlug'
      preLoaderRoute: typeof Char123LocaleChar125ServicesServiceSlugRouteImport
      parentRoute: typeof Char123LocaleChar125ServicesRoute
    }
    '/{-$locale}/products/$productSlug': {
      id: '/{-$locale}/products/$productSlug'
      path: '/$productSlug'
      fullPath: '/{-$locale}/products/$productSlug'
      preLoaderRoute: typeof Char123LocaleChar125ProductsProductSlugRouteImport
      parentRoute: typeof Char123LocaleChar125ProductsRoute
    }
  }
}

interface Char123LocaleChar125ProductsRouteChildren {
  Char123LocaleChar125ProductsProductSlugRoute: typeof Char123LocaleChar125ProductsProductSlugRoute
}

const Char123LocaleChar125ProductsRouteChildren: Char123LocaleChar125ProductsRouteChildren =
  {
    Char123LocaleChar125ProductsProductSlugRoute:
      Char123LocaleChar125ProductsProductSlugRoute,
  }

const Char123LocaleChar125ProductsRouteWithChildren =
  Char123LocaleChar125ProductsRoute._addFileChildren(
    Char123LocaleChar125ProductsRouteChildren,
  )

interface Char123LocaleChar125ServicesRouteChildren {
  Char123LocaleChar125ServicesServiceSlugRoute: typeof Char123LocaleChar125ServicesServiceSlugRoute
}

const Char123LocaleChar125ServicesRouteChildren: Char123LocaleChar125ServicesRouteChildren =
  {
    Char123LocaleChar125ServicesServiceSlugRoute:
      Char123LocaleChar125ServicesServiceSlugRoute,
  }

const Char123LocaleChar125ServicesRouteWithChildren =
  Char123LocaleChar125ServicesRoute._addFileChildren(
    Char123LocaleChar125ServicesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125AuthRoute: Char123LocaleChar125AuthRoute,
  Char123LocaleChar125BusinessRoute: Char123LocaleChar125BusinessRoute,
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125DashboardRoute: Char123LocaleChar125DashboardRoute,
  Char123LocaleChar125FreelancingRoute: Char123LocaleChar125FreelancingRoute,
  Char123LocaleChar125IndustriesRoute: Char123LocaleChar125IndustriesRoute,
  Char123LocaleChar125ProductsRoute:
    Char123LocaleChar125ProductsRouteWithChildren,
  Char123LocaleChar125ServicesRoute:
    Char123LocaleChar125ServicesRouteWithChildren,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
